package appforms;

public interface Consts{
	public static String
		LINK_TYPE_TEXT="text",
		LINK_TYPE_FILE="file",
		LINK_TYPE_FILES="files",
		READ_TYPE_SHARE="share",
		READ_TYPE_FILE="openfile",
		READ_TYPE_TEXT="copytext",
		CREATE_SOURCE_DESKTOP="from_desktop";
	public static final int
		ACTIVITY_FOR_RESULT_SELECTED_FILE=37,
		ACTIVITY_FOR_RESULT_CROP_IMAGE_CONFIRMED=45,
		ACTIVITY_FOR_RESULT_CROP_IMAGE_FINISHED=46,
		ACTIVITY_FOR_RESULT_CREATE_SOURCE_DESKTOP=52,
		ACTIVITY_FOR_RESULT_SELECTED_IMAGE=78,
		ACTIVITY_FOR_RESULT_SELECTED_ACTIVITY=79;
}
